# Usa una imagen base de Python
FROM python:3.11

# Actualiza e instala las dependencias necesarias, junto con Firefox
RUN apt-get update \
    && apt-get install -y firefox-esr \
    && apt-get -y install coreutils \ 
    && rm -rf /var/lib/apt/lists/* \
    && which firefox

# Install Firefox and GeckoDriver
### RUN apt-get update && apt-get install -y firefox-esr
ADD https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz /usr/local/bin/
RUN tar -xzf /usr/local/bin/geckodriver-v0.34.0-linux64.tar.gz -C /usr/local/bin/

# Then install GeckoDriver
### wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
### tar -zxf geckodriver-v0.26.0-linux64.tar.gz -C /usr/bin
### geckodriver --version

### RUN mkdir /browsers \
###     && curl https://ftp.mozilla.org/pub/firefox/releases/61.0.1/linux-x86_64/en-US/firefox-61.0.1.tar.bz2 -o /browsers/firefox-61.0.1.tar.bz2 \
###     && cd browsers/ \
###     && tar xvf firefox-61.0.1.tar.bz2 -C /browsers \
###     && chmod +x browsers/firefox

### RUN mkdir /drivers/ \
###     && curl -L https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz -o /drivers/geckodriver.tar.gz \
###     && tar -xzvf /drivers/geckodriver.tar.gz -C /usr/bin
###     && tar -xzvf /drivers/geckodriver.tar.gz -C /drivers/ \
###     && chmod +x drivers/geckodriver

# Set the working directory
WORKDIR /selenium_tests/

# Copy the folder with the tests into the container
COPY selenium_tests/ /selenium_tests/

# Install all dependencies
RUN pip install -r requirements.txt

# Ejecutar las pruebas
RUN pytest -v