version: '3'
services:
  pytest_host:
    networks:
      selenium_net: {}
    build: .
    depends_on:
     - selenium-hub
     - selenium-firefox
  selenium-hub:
    image: selenium/hub:4.0.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
  selenium-firefox:
    networks:
      selenium_net: {}
    image: selenium/node-firefox:4.0.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
    - 5555
networks:
  selenium_net:
    driver: bridge