version: '3.8'

services:
  pytest-host:
    container_name: pytest-host
    build: .
    depends_on:
     - selenium-hub
     - selenium-firefox
    entrypoint: ["./wait-for-it.sh", "-t", "15", "selenium-firefox:5555", "--"]
    # the wait-for-it.sh command makes the container wait until the Selenium containers are ready to work
    command: [
      "pytest", "--remote", "--rmt-host=selenium-hub", "--rmt-port=4444"
    ]
    volumes:
      - ./remote_reports/:/selenium_tests/reports/
    networks:
      selenium_net: {}

  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:3.141.59
    ports:
      - "4444:4444"
    networks:
      selenium_net: {}

  selenium-firefox:
    container_name: selenium-firefox
    image: selenium/node-firefox:3.141.59
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      selenium_net: {}
    expose:
      - 5555

networks:
  selenium_net:
    driver: bridge