version: '3.8'

services:
  pytest-host:
    container_name: pytest-host
    build: .
    depends_on:
     - selenium-hub
     - selenium-firefox
    command: ./wait-for-it.sh -t 15 selenium-firefox:4444 -- pytest -v --remote
    networks:
      selenium_net: {}

  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:4.0.0
    ports:
      - "4444:4444"
    networks:
      selenium_net: {}

  selenium-firefox:
    container_name: selenium-firefox
    image: selenium/node-firefox:4.0.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      selenium_net: {}

networks:
  selenium_net:
    driver: bridge